### ISSUE TITLE
Fix sniper

### ISSUE THREAD

**Issue by chanios** [DeekitWises/angpao-sniper#1]
ต้าชั่วเท่อชั่ว ปู๋ย่าวหลาย อูหลูหว่อเตอเหม่ย หว่อปูซื่อหนี่เตอสไตล์ โย่วเว่ยเหอเทียนเทียนฉันเจอเหว่อ ต้าชั่ว ปู๋ย่วนหลาย อูหลูหว่อเตอเหม่ย ตั้นย่าวซื่อหนี่ ลีฮวานหว่อโจ้วคว่ายเตี่ยน ต้าเชิงชัวชูหลาย เย้

**Comment by chanios** [comment]
ต้าชั่วเท่อชั่ว ปู๋ย่าวหลาย

อูหลูหว่อเตอเหม่ย

หว่อปูซื่อหนี่เตอสไตล์

โย่วเว่ยเหอเทียนเทียนฉันเจอเหว่อ

ต้าชั่ว ปู๋ย่วนหลาย

อูหลูหว่อเตอเหม่ย

ตั้นย่าวซื่อหนี่ ลีฮวานหว่อโจ้วคว่ายเตี่ยน

ต้าเชิงชัวชูหลาย เย้...

**Comment by DeekitWises** [comment]
this issue has been fixed

**Comment by DeekitWises** [comment]
https://gift.truemoney.com/campaign/?v=6d81eb5bb0e14b4186f244261dd7b763e7d
